# Generated by Django 5.1.7 on 2025-03-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('IMPORTANT', 'Important'), ('INFO', 'Information'), ('EVENT', 'Évènement')], default='INFO', max_length=10)),
                ('contenu', models.TextField()),
                ('auteur', models.CharField(choices=[('DRH', 'Direction des Ressources Humaines'), ('DIT', 'Direction des Technologies'), ('DG', 'Direction Générale')], max_length=10)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('categorie', models.CharField(choices=[('RAPPORT', 'Rapport'), ('FORMULAIRE', 'Formulaire'), ('PRESENTATION', 'Présentation'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('contenuFichier', models.FileField(upload_to='documents/')),
                ('notes', models.ManyToManyField(blank=True, related_name='documents', to='notes.note')),
            ],
        ),
    ]
